### ISSUE TITLE
Prefix events

### ISSUE THREAD

**Issue by pietercolpaert** [rubensworks/rdf-parse.js#22]
A feature request for developers:

When working with data in JavaScript, and in order to pretty-print it later on, it’s useful to know what prefixes were used in the original file. Could we emit `prefix` events for when a parser encounters a new prefix? Of course only to be implemented for these serializations that support prefixes.

**Comment by rubensworks** [comment]
Good idea, should be easy to implement.
In theory the only thing that we'd need to do is forward the prefix events from [Comunica's quad stream](https://github.com/rubensworks/rdf-parse.js/blob/master/lib/RdfParser.ts#L87) and delegate it to our [`readable`](https://github.com/rubensworks/rdf-parse.js/blob/master/lib/RdfParser.ts#L75).

**Comment by fvitali** [comment]
I am not sure what is going on: if it is my implementation error, or there is still something missing: I can already get working callbacks for the "prefix" and the "context" events (json+ld of course), but they seem to have no parameters specified: 

`rdfParser.parse(textStream, { contentType: syntax })
		.on('prefix', (a) => { console.log(a) })
		.on('context', (b) => {  console.log(b) })
		.on('data', (quad) => { data.push(quad) })
		.on('error', (e) => { reject({ error: e} ) })
		.on('end', () => { resolve({quads: data}) 
`

both functions get executed, and both print "undefined" on the console. 

Can you help?

**Comment by rubensworks** [comment]
@fvitali I'm surprised that prints anything to be honest.
In any case, this feature is not implemented yet, so it's normal that it's not working as intended.

You're welcome to submit a PR though! :-)

**Comment by fvitali** [comment]
I submitted two separate Pull requests, one here and another on N3.js, to fully enable support for prefix and context callbacks. 

I am not really sure about the N3.js, as I was not able to fully follow the complex chain of required module. Anyway, this now works for me.
