### ISSUE TITLE
Having trouble passing JSON-LD context using options

### ISSUE THREAD

**Issue by howarddierking** [rubensworks/rdf-parse.js#41]
Apologies for not having bottomed out tracing, but I got turned around in the action dispatching code and the translation from TS to JS. I'm trying to parse JSON-LD with the context passed in through options rather than specified inline in the data stream. All of the documentation seems to suggest that this should be doable via a `context` property on the `options` object - however, it doesn't seem to be picking that member up in the parser because my returned quad stream has 0 members.

Here's the test that I'm trying to run to verify...

```
context.only('when loading a JSON-LD graph from an in-memory string', () => {
    const jsonLdInput = '{"@id": "policy/f9ee1b01-5eb4-4fa7-91ac-6877e00e32e6","@type": "Policy","expenseTypeLimit": {"expenseType": { "@id": "expense-type/fe382b00-003f-4bd5-a490-79b052b89446" },"employee": { "@id": "user/d20a1b6b-6e9f-4bc9-b313-dd58f0a5d106" },"blockingExpenseTypeLimit": {"@type": "xsd:double","@value": "100.10"},"warningExpenseTypeLimit": {"@type": "xsd:double","@value": "50.00"}}}';
    const context = {
        '@vocab': "https://schema.acme.com/",
        '@base': 'https://graph.acme.com/',
        'xsd': 'http://www.w3.org/2001/XMLSchema#'
    };

    let data;

    beforeEach(() => {
        data = Readable.from(jsonLdInput);
    });

    it('should have the correct number of nodes', async () => {
        const ds = await load({ contentType: contentTypes.jsonld, context }, data);
        ds.size.should.eql(6);
    });
});
```

and here's the code that it's exercising that uses `rdf-parse`

```
export const load = R.curry(async (options, data) => {
  return new Promise((resolve, reject) => {
    const ds = rdf.dataset();

    rdfParser.default.parse(data, options)
    .on('data', q => {
      ds.add(quadMod(options)(q));
    })
    .on('error', e => {
      // console.error(e);
      reject(new Error('Unable to parse data as an RDF dataset'));
    })
    .on('end', () => {
      debugger
      resolve(ds);
    });
  });
});
```

Again, apologies if this is just stupid user error, but I've been stuck on it long enough now that I wanted to reach out and ask for help.

**Comment by rubensworks** [comment]
> All of the documentation seems to suggest that this should be doable via a context property on the options object 

This is unfortunately not possible (but I agree that it would be a great feature to have).

It should however be possible with a following workaround. By passing an object with the key `"@comunica/actor-rdf-parse-jsonld:parserOptions"` to the `options` object, this object will be forwarded to the JSON-LD parser's options: https://github.com/rubensworks/jsonld-streaming-parser.js#configuration
So within that object, you can pass a custom `context`.

**Comment by howarddierking** [comment]
thanks @rubensworks! I was already encapsulating the call to the parser in a function, so just added the following to get it working.

```
if(options.context){
    options['@comunica/actor-rdf-parse-jsonld:parserOptions'] = options;
};
```

It may not be the most beautiful code in the world, but it's small enough to where I'm not going to lose sleep over it.
