### ISSUE TITLE
Needless circular import between index and engine-default

### ISSUE THREAD

**Issue by jgonggrijp** [rubensworks/rdf-parse.js#9]
The index module re-exports both the named exports from lib/RdfParser and the default export from engine-default. This makes sense.

The engine-default module imports `RdfParser` from the index. This does not make sense; it could import that class directly from lib/RdfParser instead. This also breaks rollup builds.

I would submit a pull request with a fix, but the engine-default module is automagically generated from an RDF DSL that I don't sufficiently understand (it does look cool, though!). Could you help me out, @rubensworks?

For the time being, I work around this by importing the default from `rdf-parse/engine-default` instead of from `rdf-parse`.

**Comment by rubensworks** [comment]
Thanks for reporting this!
Circular imports are not a good thing indeed.
I've modified the import of the `engine-default.js` file as suggested.

Fixed in 1.2.1.
